"use client";
import Link from "next/link";
import {useState} from "react";
import {Page as Layout,PageHeader,Surface,Section} from "@/components/foundation/layout/layout";
import {Button} from "@/components/arc/button/button";
import {Textarea} from "@/components/arc/textarea/textarea";
import {HoldToConfirm} from "@/components/arc/hold-to-confirm/hold-to-confirm";
import {call,useResource,useAction,Feedback,Empty,ResourceError,More} from "./common";
import {Sessions,Files} from "./device-detail";
import type {Account,Silicon,Page,Grant,Request} from "@/lib/product/types";
import styles from "./product.module.css";
export function Silicons(){const q=useResource<Page<Silicon>>("/api/v2/silicons");return <Layout><PageHeader title="Your Silicons" description="The Silicons you look after, and the ones you have given access."/><ResourceError error={q.error}/><div className={styles.grid}>{q.data?.items.map(s=><Link key={s.uuid} href={`/silicons/${encodeURIComponent(s.id)}`} data-sq="surface" className={styles.card}><h2>{s.display_name||s.id}</h2><p className={styles.muted}>{s.id}</p><p>{s.running_sessions??0} running sessions · {s.grants??s.granted_by_you??0} grants</p></Link>)}</div>{!q.data?.items.length?<Surface><Empty>Your Silicons will appear after they sign in to Extend or receive device access.</Empty></Surface>:null}</Layout>;}
export function SiliconDetail({id}:{id:string}){const q=useResource<Silicon>(`/api/v2/silicons/${encodeURIComponent(id)}`);const grants=useResource<Page<Grant>>(`/api/v2/silicons/${encodeURIComponent(id)}/grants`);const action=useAction();return <Layout><PageHeader title={q.data?.display_name||id} description="See and manage its access. Sessions always run as the Silicon itself." back={{href:"/silicons",label:"Your Silicons"}}/><ResourceError error={q.error}/><Feedback action={action}/><Section title="Device access"><Surface><ResourceError error={grants.error}/>{grants.data?.items.map(g=><div className={styles.item} key={g.device_id}><div className={styles.spread}><div><strong>{g.device_name||g.device_id}</strong><p className={styles.muted}>Granted by {g.granted_by}</p></div><HoldToConfirm label="Hold to renounce access" onConfirm={()=>void action.run(()=>call(`/api/v2/silicons/${encodeURIComponent(id)}/grants/${g.device_id}`,{method:"DELETE"}),"Access renounced")}/></div></div>)}{!grants.data?.items.length?<Empty>No device grants.</Empty>:null}</Surface></Section>{q.data?.looked_after?<><Sessions query={`silicon=${encodeURIComponent(id)}`}/><Files query={`silicon=${encodeURIComponent(id)}`}/><RequestsList query={`silicon=${encodeURIComponent(id)}`}/></>:null}</Layout>;}
export function Requests(){return <Layout><PageHeader title="Requests" description="Requests to use devices, visible here even when notifications are off."/><RequestsList query=""/></Layout>;}
function RequestsList({query}:{query:string}){const [cursor,setCursor]=useState("");const q=useResource<Page<Request>>(`/api/v2/requests?${query}${cursor?`&cursor=${cursor}`:""}`);return <Section title="Device-use requests"><Surface><ResourceError error={q.error}/>{q.data?.items.map(r=><div key={r.request_id} className={styles.item}><div className={styles.spread}><strong>{r.from}</strong><Link href={`/devices/${r.device_id}`}>Open device</Link></div><p>{r.reason}</p><p className={styles.muted}>{r.delivery} · {new Date(r.created_at).toLocaleString()}</p></div>)}{!q.data?.items.length?<Empty>No requests yet. Wake requests appear on each device’s Requests tab.</Empty>:null}<More cursor={q.data?.next_cursor} onMore={()=>setCursor(q.data?.next_cursor??"")}/></Surface></Section>;}
export function Settings({me}:{me:Account}){const q=useResource<{ting_enabled:boolean}>("/api/v2/accounts");const [message,setMessage]=useState("");const action=useAction();return <Layout width="narrow"><PageHeader title="Settings" description="Your account and delivery preferences."/><Section title="Account"><Surface><strong>{me.display_name||me.id}</strong><p className={styles.muted}>{me.id}</p><p><a href="https://accounts.teamofsilicons.com">Manage your Silicon Accounts profile →</a></p><p>Use the account menu to switch light, dark, or system appearance. Signing out ends the sessions on the device pairings you granted.</p></Surface></Section><Section title="Notifications"><Surface><ResourceError error={q.error}/><p>{q.data?.ting_enabled?"Ting notifications are available.":"Ting notifications are off. Requests remain visible here, in the command line and on the device."}</p>{q.data?.ting_enabled?<Button onClick={()=>void action.run(()=>call("/api/v2/ting-registration",{method:"PUT"}),"Notifications enabled")}>Enable notifications</Button>:null}</Surface></Section><Section title="Report a problem"><Surface><form className={styles.form} onSubmit={e=>{e.preventDefault();void action.run(async()=>{await call("/api/v2/reports",{method:"POST",body:{type:"report",data:{message,client_version:"web-4.0.0"}},idempotencyKey:true});setMessage("");},"Report sent");}}><Textarea label="What happened?" required value={message} onChange={e=>setMessage(e.target.value)}/><Button type="submit" loading={action.busy}>Send report</Button><Feedback action={action}/></form></Surface></Section></Layout>;}
