"use client";
import Link from "next/link";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {MonitorSmartphone,ArrowUpRight} from "lucide-react";
import {Page as Layout,PageHeader,Surface,Section} from "@/components/foundation/layout/layout";
import {Button} from "@/components/arc/button/button";
import {Input} from "@/components/arc/input/input";
import {call,useResource,useAction,Feedback,Empty,ResourceError,More} from "./common";
import type {Device,Page} from "@/lib/product/types";
import styles from "./product.module.css";
export function Devices({initial}:{initial:Page<Device>}){const [search,setSearch]=useState("");const [removed,setRemoved]=useState(false);const [cursor,setCursor]=useState("");const q=useResource<Page<Device>>(`/api/v2/devices?scope=mine&limit=50${removed?"&include_removed=true":""}${cursor?`&cursor=${cursor}`:""}`,removed||cursor?undefined:initial);const items=q.data?.items.filter(d=>d.name.toLowerCase().includes(search.toLowerCase()));return <Layout><PageHeader title="Your devices" description="A place for your Silicons to work. You decide the access." actions={<Link href="/devices/new">Add a device →</Link>}/><div className={styles.row}><Input label="Find a device" value={search} onChange={e=>setSearch(e.target.value)}/><label className={styles.check}><input type="checkbox" checked={removed} onChange={e=>setRemoved(e.target.checked)}/>Show removed devices</label></div><ResourceError error={q.error}/><div className={styles.grid}>{items?.map(d=><Link data-sq="surface" className={styles.card} key={d.device_id} href={`/devices/${d.device_id}`}><div className={styles.spread}><MonitorSmartphone size={26} className={styles.icon}/><ArrowUpRight size={18}/></div><h2>{d.name}</h2><p className={styles.muted}>{d.os.replaceAll("_"," ")} · {d.kind}</p><strong>{d.removed_at?"Removed":d.in_use?`In use by ${d.in_use.silicon_id}`:d.in_use_by_other?"In use":d.online?d.awake===false?"Asleep":"Ready":"Offline"}</strong><p className={styles.muted}>{d.days_left!==undefined?`${d.days_left} days left on this pairing`:""}</p></Link>)}</div>{!items?.length?<Surface><Empty>{search?"No devices match this name.":"Pair your first device to give a Silicon somewhere to work."}<br/><Link href="/devices/new">Add a device</Link></Empty></Surface>:null}<More cursor={q.data?.next_cursor} onMore={()=>setCursor(q.data?.next_cursor??"")}/></Layout>;}
export function AddDevice(){const [method,setMethod]=useState("code");const [code,setCode]=useState("");const [name,setName]=useState("");const [ttl,setTtl]=useState(14);const [banner,setBanner]=useState(true);const [host,setHost]=useState("");const [os,setOs]=useState("ios");const [address,setAddress]=useState("");const [paired,setPaired]=useState<Device|null>(null);const q=useResource<Page<Device>>("/api/v2/devices?scope=mine&limit=100");const action=useAction();const router=useRouter();
const finish=async()=>{let d=paired;if(!d){d=await call<Device>(method==="code"?"/api/v2/pairings":`/api/v2/devices/${host}/attachments`,{method:"POST",body:{type:method==="code"?"pairing":"attachment",data:{name,pair_ttl_days:ttl,...(method==="code"?{pairing_code:code}:{os,...(address?{address}:{})})}},idempotencyKey:true});setPaired(d);}if(!banner)await call(`/api/v2/devices/${d.device_id}`,{method:"PATCH",body:{type:"device",data:{in_use_indicator:"hidden"}},headers:{"If-Match":`"${d.version}"`}});router.push(`/devices/${d.device_id}`);};
return <Layout width="narrow"><PageHeader title="Add a device" description="Pair it with your account, then choose which Silicons may use it." back={{href:"/devices",label:"Devices"}}/><Section title="1. Get the device ready"><Surface><p>Install Extend on your computer or Android device, then open it to see a pairing code.</p><p><Link href="/downloads">Download the device apps →</Link></p><p className={styles.muted}>An iPhone, iPad or TV connects through a computer you already paired.</p></Surface></Section><Section title="2. Pair the device"><Surface><form className={styles.form} onSubmit={e=>{e.preventDefault();void action.run(finish,"Device paired");}}><label className={styles.field}>Connection<select data-sq="surface" className={styles.select} value={method} disabled={!!paired} onChange={e=>setMethod(e.target.value)}><option value="code">A pairing code</option><option value="host">Through my computer</option></select></label>{method==="code"?<Input label="Pairing code" required value={code} disabled={!!paired} onChange={e=>setCode(e.target.value)}/>:<><label className={styles.field}>Computer<select required className={styles.select} data-sq="surface" value={host} onChange={e=>setHost(e.target.value)}><option value="">Choose a paired computer</option>{q.data?.items.filter(d=>d.kind==="computer"&&!d.removed_at).map(d=><option key={d.device_id} value={d.device_id}>{d.name}</option>)}</select></label><label className={styles.field}>Device type<select data-sq="surface" className={styles.select} value={os} onChange={e=>setOs(e.target.value)}>{["ios","ipados","tvos","samsung_tv","lg_tv"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><Input label="TV network address (optional)" value={address} onChange={e=>setAddress(e.target.value)}/></>}<Input label="Device name" required maxLength={64} disabled={!!paired} value={name} onChange={e=>setName(e.target.value)}/><Input label="Pairing lifetime in days" type="number" min={1} max={30} value={ttl} onChange={e=>setTtl(Number(e.target.value))}/><label className={styles.check}><input type="checkbox" checked={banner} onChange={e=>setBanner(e.target.checked)}/>Show a banner while a Silicon is using this device</label><p className={styles.muted}>This banner setting applies to the device, including its other pairings. You can change it later.</p><Button type="submit" loading={action.busy}>{paired?"Finish device settings":"Pair device"}</Button><Feedback action={action}/></form></Surface></Section></Layout>;
}
