"use client";
/* eslint-disable @next/next/no-img-element -- Device captures stream through the authenticated same-origin proxy. */
import Link from "next/link";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {Page as Layout,PageHeader,Surface,Section} from "@/components/foundation/layout/layout";
import {Button} from "@/components/silicon-ui/button/button";
import {Input} from "@/components/silicon-ui/input/input";
import {HoldToConfirm} from "@/components/silicon-ui/hold-to-confirm/hold-to-confirm";
import {call,useResource,useAction,Feedback,Empty,ResourceError,More} from "./common";
import type {Device,Grant,Session,FileInfo,Activity,Setup,Page,Wake,Request} from "@/lib/product/types";
import styles from "./product.module.css";
export function DeviceDetail({initial}:{initial:Device}){const id=initial.device_id;const root=`/api/v2/devices/${id}`;const q=useResource<Device>(root,initial);const d=q.data??initial;const [name,setName]=useState(d.name);const [ttl,setTtl]=useState(d.pair_ttl_days??14);const [banner,setBanner]=useState(d.in_use_indicator!=="hidden");const [silicon,setSilicon]=useState("");const [tab,setTab]=useState("overview");const action=useAction();const router=useRouter();const grants=useResource<Page<Grant>>(`${root}/access`);
return <Layout><PageHeader title={d.name} size="entity" description={`${d.os.replaceAll("_"," ")} · ${d.online?d.awake===false?"Asleep":"Online":"Offline"} · ${d.state}`} back={{href:"/devices",label:"Devices"}}/><Feedback action={action}/><ResourceError error={q.error}/>{d.in_use||d.in_use_by_other?<Surface><div className={styles.spread}><p>{d.in_use?`In use by ${d.in_use.silicon_id}`:"In use through another pairing"}</p><HoldToConfirm label="Hold to stop session" tone="danger" onConfirm={()=>void action.run(()=>call(`${root}/stop`,{method:"POST"}),"Session stopped")}/></div>{d.in_use_by_other_carried?<p>Stop this session from the computer that carries this device.</p>:null}</Surface>:null}
<div className={styles.tabs} role="tablist" aria-label="Device details" onKeyDown={e=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(e.key))return;e.preventDefault();const tabs=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('[role="tab"]'));const current=tabs.findIndex(t=>t===document.activeElement);const next=e.key==="Home"?0:e.key==="End"?tabs.length-1:(current+(e.key==="ArrowRight"?1:-1)+tabs.length)%tabs.length;tabs[next]?.focus();tabs[next]?.click();}}>{["overview","access","sessions","recordings","activity","requests"].map(t=><Button key={t} role="tab" id={`device-tab-${t}`} aria-controls="device-panel" tabIndex={tab===t?0:-1} aria-selected={tab===t} variant={tab===t?"primary":"ghost"} onClick={()=>{setTab(t);action.reset();}}>{t[0].toUpperCase()+t.slice(1)}</Button>)}</div>
<div id="device-panel" role="tabpanel" aria-labelledby={`device-tab-${tab}`} tabIndex={0}>{tab==="overview"?<div className={styles.columns}><div className={styles.stack}><Section title="Device settings"><Surface><form className={styles.form} onSubmit={e=>{e.preventDefault();void action.run(()=>call(root,{method:"PATCH",body:{type:"device",data:{name,pair_ttl_days:ttl,in_use_indicator:banner?"shown":"hidden"}},headers:{"If-Match":`"${d.version}"`}}),"Device settings saved");}}><Input required label="Device name" value={name} onChange={e=>setName(e.target.value)}/><Input label="Pairing lifetime in days" type="number" min={1} max={30} value={ttl} onChange={e=>setTtl(Number(e.target.value))}/><label className={styles.check}><input type="checkbox" checked={banner} onChange={e=>setBanner(e.target.checked)}/>Show a banner while a Silicon is using this device</label><Button type="submit" loading={action.busy} disabled={!!d.removed_at}>Save settings</Button></form></Surface></Section>{d.state==="setup"?<SetupSteps root={root}/>:null}</div><div className={styles.stack}><Section title="Capabilities"><Surface><p>{d.capabilities?.join(", ")||"Capabilities appear when the device connects."}</p>{d.missing?.map(m=><p key={m.capability} className={styles.muted}>{m.capability}: {m.reason}</p>)}<p className={styles.muted}>App {d.app_version??"unknown"} · Engine {d.engine_version??"unknown"}</p>{d.host_device_id?<Link href={`/devices/${d.host_device_id}`}>Open host computer</Link>:null}</Surface></Section><Section title="Pairing"><Surface><p>{d.days_left??"—"} days left</p><p className={styles.muted}>Removing this pairing ends the access you granted here.</p><HoldToConfirm label="Hold to remove device" tone="danger" disabled={!!d.removed_at} onConfirm={()=>void action.run(async()=>{await call(root,{method:"DELETE",headers:{"If-Match":`"${d.version}"`}});router.push("/devices");},"Device removed")}/></Surface></Section></div></div>:null}
{tab==="access"?<Section title="Silicons with access" description="Grant access by si: id. Taking it away ends their active sessions on this pairing."><Surface><ResourceError error={grants.error}/>{grants.data?.items.map(g=><div key={g.silicon_id} className={styles.item}><div className={styles.spread}><div><strong>{g.silicon_id}</strong><p className={styles.muted}>Granted {new Date(g.granted_at).toLocaleDateString()}</p></div><HoldToConfirm label="Hold to revoke access" onConfirm={()=>void action.run(()=>call(`${root}/access/${encodeURIComponent(g.silicon_id)}`,{method:"DELETE"}),"Access revoked")}/></div><Button variant="ghost" size="sm" onClick={()=>void action.run(()=>call(`${root}/wake-settings`,{method:"PUT",body:{type:"wake_settings",data:{silicon_id:g.silicon_id,muted:!g.wake_muted}}}),"Wake settings saved")}>{g.wake_muted?"Allow wake requests":"Mute wake requests"}</Button></div>)}{!grants.data?.items.length?<Empty>No Silicons have access yet.</Empty>:null}<form className={styles.form} onSubmit={e=>{e.preventDefault();void action.run(async()=>{await call(`${root}/access/${encodeURIComponent(silicon.trim())}`,{method:"PUT"});setSilicon("");},"Access granted");}}><Input label="Silicon id" placeholder="si:scout" required pattern="si:.+" value={silicon} onChange={e=>setSilicon(e.target.value)}/><Button type="submit" loading={action.busy}>Grant access</Button></form></Surface></Section>:null}
{tab==="sessions"?<Sessions query={`device_id=${id}`}/>:null}{tab==="recordings"?<Files query={`device_id=${id}`}/>:null}{tab==="activity"?<ActivityFeed root={root}/>:null}{tab==="requests"?<DeviceRequests root={root} muted={d.wake_muted??false}/>:null}</div></Layout>;
}
function SetupSteps({root}:{root:string}){const q=useResource<Setup>(`${root}/setup`);const [code,setCode]=useState("");const action=useAction();return <Section title="Complete setup"><Surface><ResourceError error={q.error}/><Feedback action={action}/>{q.data?.steps.map(s=><div key={s.key} className={styles.item}><h3>{s.title} · {s.status.replaceAll("_"," ")}</h3><p>{s.help}</p>{s.error?<p className={styles.danger}>{s.error}</p>:null}{s.input?<form className={styles.form} onSubmit={e=>{e.preventDefault();void action.run(()=>call(`${root}/setup/code`,{method:"POST",body:{type:"setup_code",data:{code}}}),"Code sent");}}><Input label="Code shown on the device" required value={code} onChange={e=>setCode(e.target.value)}/><Button type="submit">Send code</Button></form>:null}{s.status==="failed"?<Button variant="secondary" onClick={()=>void action.run(()=>call(`${root}/setup/retry`,{method:"POST",body:{type:"setup_retry",data:{step:s.key}}}),"Setup retry requested")}>Retry {s.title}</Button>:null}</div>)}</Surface></Section>;}
export function Sessions({query}:{query:string}){const [cursor,setCursor]=useState("");const q=useResource<Page<Session>>(`/api/v2/sessions?${query}${cursor?`&cursor=${cursor}`:""}`);const action=useAction();return <Section title="Sessions"><Surface><ResourceError error={q.error}/><Feedback action={action}/>{q.data?.items.map(s=><div key={s.session_id} className={styles.item}><div className={styles.spread}><div><strong>{s.silicon_id}</strong><p>{s.state} · {s.command_count??0} commands</p><p className={styles.muted}>{new Date(s.started_at).toLocaleString()} {s.end_reason?`· ${s.end_reason.replaceAll("_"," ")}`:""}</p></div>{s.state!=="ended"?<HoldToConfirm label="Hold to end session" onConfirm={()=>void action.run(()=>call(`/api/v2/sessions/${s.session_id}/end`,{method:"POST"}),"Session ended")}/>:null}</div></div>)}{!q.data?.items.length?<Empty>Sessions will appear when a Silicon uses a device.</Empty>:null}<More cursor={q.data?.next_cursor} onMore={()=>setCursor(q.data?.next_cursor??"")}/></Surface></Section>;}
export function Files({query}:{query:string}){const [cursor,setCursor]=useState("");const q=useResource<Page<FileInfo>>(`/api/v2/files?${query}${cursor?`&cursor=${cursor}`:""}`);const action=useAction();return <Section title="Recordings & files"><Surface><ResourceError error={q.error}/><Feedback action={action}/>{q.data?.items.map(f=><div className={styles.item} key={f.file_id}><h3>{f.name}</h3><p className={styles.muted}>{f.kind} · {(f.size_bytes/1024).toFixed(1)} KB · {f.permanent?"Kept":`Expires ${f.self_destruct_at?new Date(f.self_destruct_at).toLocaleString():"automatically"}`}</p>{f.content_type.startsWith("image/")?<img style={{maxWidth:"100%",maxHeight:320}} src={`/api/api/v2/files/${f.file_id}/content`} alt={f.name}/>:null}{f.content_type.startsWith("video/")?<video className={styles.attachments} style={{maxWidth:"100%"}} controls src={`/api/api/v2/files/${f.file_id}/content`}/>:null}{f.content_type.startsWith("audio/")?<audio controls src={`/api/api/v2/files/${f.file_id}/content`}/>:null}<div className={styles.actions}><a href={`/api/api/v2/files/${f.file_id}/content`} download={f.name}>Download</a>{!f.permanent?<Button variant="secondary" onClick={()=>void action.run(()=>call(`/api/v2/files/${f.file_id}/keep`,{method:"POST"}),"File kept")}>Keep file</Button>:null}</div></div>)}{!q.data?.items.length?<Empty>Recordings and captures appear here after a session creates them.</Empty>:null}<More cursor={q.data?.next_cursor} onMore={()=>setCursor(q.data?.next_cursor??"")}/></Surface></Section>;}
function ActivityFeed({root}:{root:string}){const [cursor,setCursor]=useState("");const q=useResource<Page<Activity>>(`${root}/activity${cursor?`?cursor=${cursor}`:""}`);return <Section title="Device activity"><Surface><ResourceError error={q.error}/>{q.data?.items.map(a=><div className={styles.item} key={a.id}><strong>{a.action.replaceAll("_"," ")}</strong><p>{a.actor.display_name||a.actor.id} {a.command?`· ${a.command}`:""} {a.outcome?`· ${a.outcome}`:""}</p><p className={styles.muted}>{new Date(a.at).toLocaleString()}</p></div>)}{!q.data?.items.length?<Empty>Activity appears as the device is used.</Empty>:null}<More cursor={q.data?.next_cursor} onMore={()=>setCursor(q.data?.next_cursor??"")}/></Surface></Section>;}
function DeviceRequests({root,muted}:{root:string;muted:boolean}){const wakes=useResource<Page<Wake>>(`${root}/wake-requests?state=all`);const requests=useResource<Page<Request>>(`${root}/requests`);const action=useAction();return <div className={styles.stack}><Section title="Wake requests"><Surface><Feedback action={action}/><ResourceError error={wakes.error}/><Button variant="secondary" onClick={()=>void action.run(()=>call(`${root}/wake-settings`,{method:"PUT",body:{type:"wake_settings",data:{muted:!muted}}}),"Wake settings saved")}>{muted?"Allow wake requests":"Mute wake requests"}</Button>{wakes.data?.items.map(w=><div className={styles.item} key={w.wake_id}><h3>{w.from}</h3><p>{w.reason}</p><p className={styles.muted}>{w.state} · {w.device_notice_note||w.device_notice}</p>{w.state==="open"?<div className={styles.actions}>{["woken","declined"].map(answer=><Button key={answer} variant={answer==="woken"?"primary":"secondary"} onClick={()=>void action.run(()=>call(`${root}/wake-requests/answer`,{method:"POST",body:{type:"wake_answer",data:{answer,wake_ids:[w.wake_id]}}}),"Wake request answered")}>{answer==="woken"?"It’s awake":"Decline"}</Button>)}</div>:null}</div>)}{!wakes.data?.items.length?<Empty>No wake requests.</Empty>:null}</Surface></Section><Section title="Device-use requests"><Surface><ResourceError error={requests.error}/>{requests.data?.items.map(r=><div className={styles.item} key={r.request_id}><strong>{r.from}</strong><p>{r.reason}</p><p className={styles.muted}>{r.delivery} · {new Date(r.created_at).toLocaleString()}</p></div>)}{!requests.data?.items.length?<Empty>No device-use requests.</Empty>:null}</Surface></Section></div>;}
