# `cargo about generate about.hbs -o THIRD_PARTY_LICENSES.txt` writes the licence text of every Rust
# dependency that ships in Extend's binaries. Regenerate it whenever Cargo.lock changes.
accepted = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-1-Clause",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
    "0BSD",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
workarounds = ["ring", "rustls"]
