import {expect,test} from "@playwright/test";
import {spawn,type ChildProcess} from "node:child_process";
import {readFileSync} from "node:fs";
import {join} from "node:path";
import {accountsSession,runAccounts,signIn,watchErrors,captureViews,ACCOUNTS} from "./support";
let device:ChildProcess|undefined;
test.afterEach(()=>{device?.kill();device=undefined;});
test("a Carbon pairs a native device, changes its banner, grants access, and removes it",async({browser})=>{
 const context=await accountsSession(browser,"carbon");const page=await context.newPage();const errors=watchErrors(page);await signIn(page,runAccounts().carbon.email);
 const created=await context.request.post(`${ACCOUNTS}/v1/me/silicons`,{headers:{Origin:ACCOUNTS,"Idempotency-Key":crypto.randomUUID()},data:{id:`si:extend-browser-${Date.now()}`,display_name:"Studio assistant"}});expect(created.status()).toBe(201);const identity=await created.json();const silicon=identity.silicon;
 device=spawn(join(process.cwd(),"../target/mig/debug/examples/fake_device"),["http://127.0.0.1:4221","linux"],{stdio:["ignore","pipe","pipe"]});let output="";device.stdout!.on("data",chunk=>output+=chunk.toString());await expect.poll(()=>/PAIRING_CODE (\S+)/.exec(output)?.[1],{timeout:15000}).toBeTruthy();const code=/PAIRING_CODE (\S+)/.exec(output)![1];
 await page.getByRole("link",{name:"Add a device →"}).click();await page.getByLabel("Pairing code",{exact:true}).fill(code);await page.getByLabel("Device name",{exact:true}).fill("Studio computer");await page.getByLabel("Show a banner while a Silicon is using this device").uncheck();await page.getByRole("button",{name:"Pair device",exact:true}).click();await expect(page).toHaveURL(/\/devices\/[a-zA-Z0-9]+$/);await expect(page.getByRole("heading",{level:1})).toHaveText("Studio computer");await expect(page.getByLabel("Show a banner while a Silicon is using this device")).not.toBeChecked();
 await page.getByLabel("Device name",{exact:true}).fill("Studio computer, ready");await page.getByRole("button",{name:"Save settings"}).click();await expect(page.getByText("Device settings saved",{exact:true})).toBeVisible();await expect(page.getByRole("heading",{level:1})).toHaveText("Studio computer, ready");
 await captureViews(page,"device");await page.getByRole("tab",{name:"Access",exact:true}).click();await page.getByLabel("Silicon id").fill(silicon.id);await page.getByRole("button",{name:"Grant access"}).click();await expect(page.getByText("Access granted",{exact:true})).toBeVisible();await expect(page.getByText(silicon.id,{exact:true})).toBeVisible();await captureViews(page,"device-access");
 const stack=JSON.parse(readFileSync(process.env.TEST_STACK_JSON!,"utf8"));
 const first=await fetch(`${stack.accounts_api_url}/v1/silicons/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:silicon.id,stk:identity.stk})});expect(first.status).toBe(200);const firstToken=(await first.json()).access_token;
 const short=await fetch(`${stack.accounts_api_url}/v1/me/short-lived-tokens`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${firstToken}`},body:JSON.stringify({app_id:"extend"})});expect(short.status).toBe(201);const slt=(await short.json()).slt;
 const exchanged=await fetch(`${stack.accounts_api_url}/v1/oauth/token`,{method:"POST",headers:{authorization:`Basic ${Buffer.from(`extend:${stack.apps.extend.app_secret}`).toString("base64")}`,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:silicon:params:oauth:grant-type:slt",slt})});expect(exchanged.status).toBe(200);const token=(await exchanged.json()).access_token;
 const deviceId=new URL(page.url()).pathname.split("/").at(-1)!;
 const deviceCall=async(path:string,type:string,data:object)=>{const response=await fetch(`http://127.0.0.1:4221/api/v2/${path}`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({type,data})});expect(response.ok,`${path}: ${response.status}`).toBe(true);return (await response.json()).data;};
 const session=await deviceCall("sessions","session",{device_id:deviceId});await deviceCall(`sessions/${session.session_id}/commands`,"command",{command:"screenshot",args:[]});
 await page.getByLabel("Silicon id").fill("si:no-such-silicon-e2e");await page.getByRole("button",{name:"Grant access"}).click();await expect(page.getByRole("alert")).toBeVisible();
 for(const name of ["Sessions","Recordings","Activity","Requests"]){await page.getByRole("tab",{name,exact:true}).click();await expect(page.locator("main")).toBeVisible();if(name==="Sessions")await expect(page.getByText(silicon.id,{exact:true})).toBeVisible();if(name==="Recordings"){await expect(page.getByRole("heading",{name:"screenshot.png",exact:true})).toBeVisible();const download=await page.request.get(await page.getByRole("link",{name:"Download",exact:true}).getAttribute("href")??"");expect(download.status()).toBe(200);expect((await download.body()).length).toBeGreaterThan(0);await page.getByRole("button",{name:"Keep file",exact:true}).click();await expect(page.getByText("File kept",{exact:true})).toBeVisible();}await captureViews(page,`device-${name.toLowerCase()}`);}
 await page.getByRole("tab",{name:"Sessions",exact:true}).click();const end=page.getByRole("button",{name:"Hold to end session"});await end.focus();await page.keyboard.down("Space");await page.waitForTimeout(1800);await page.keyboard.up("Space");await expect(page.getByText("Session ended",{exact:true})).toBeVisible();
 const deviceUrl=page.url();await page.goto("/downloads");await expect(page.getByRole("heading",{name:"Device apps",exact:true})).toBeVisible();await page.getByRole("link",{name:"Get the app →"}).first().click();await expect(page.getByRole("link",{name:"Android app (.apk) ↓"})).toHaveAttribute("href",/android-v1\.1\.2/);
 await page.goto("/settings");await page.getByLabel("What happened?").fill("Browser verification report");await page.getByRole("button",{name:"Send report"}).click();await expect(page.getByText("Report sent",{exact:true})).toBeVisible();
 await page.goto(deviceUrl);const remove=page.getByRole("button",{name:"Hold to remove device"});await remove.focus();await page.keyboard.down("Space");await page.waitForTimeout(1800);await page.keyboard.up("Space");await expect(page).toHaveURL(/\/devices$/);await expect(page.getByText("Studio computer, ready",{exact:true})).toHaveCount(0);
 expect(errors).toEqual([]);await context.close();
});
