#!/usr/bin/env python3
"""Writes app/src/main/res/drawable/tv_banner.xml: the 320x180 dp Android TV launcher banner.

The Extend mark in cobalt on Interface's paper, with the app's TV name set as vector outlines
(no bitmap, so it stays sharp at every TV density): "Silicon Extend" in Source Serif 4 and "TV"
in IBM Plex Mono Medium, both from the fonts bundled in res/font.

Needs fontTools (`pip install fonttools`). Run from apps/android: python3 tools/banner/make_tv_banner.py
"""
import os
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "..", "app", "src", "main", "res")
PAPER, INK, COBALT = "#FFFFFDF9", "#FF262A29", "#FF1736B8"
MARK = ("M0 22h9v9h-9zM4 13h9v9h-9zM13 9h9v9h-9zM26 22h9v9h-9zM22 31h9v9h-9zM13 35h9v9h-9zM4 31h9v9h-9z"
        "M17.5 16.79L27.21 26.5L17.5 36.21L7.79 26.5zM26 9h9v9h-9zM35 0h9v9h-9z")


def text_path(font_file, text, size, x, baseline, tracking_em):
    font = TTFont(os.path.join(RES, "font", font_file))
    upm = font["head"].unitsPerEm
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    scale = size / upm
    pen = SVGPathPen(glyphs, ntos=lambda v: ("%.2f" % v).rstrip("0").rstrip("."))
    for ch in text:
        name = cmap[ord(ch)]
        glyphs[name].draw(TransformPen(pen, (scale, 0, 0, -scale, x, baseline)))
        x += glyphs[name].width * scale + tracking_em * size
    return pen.getCommands(), x


def main():
    mark_size = 52.0
    mark_x, mark_y = 30.0, 90.0 - mark_size / 2
    text_x = mark_x + mark_size + 20
    # Two lines centred on the mark: the name's cap height (0.67 em) down to the TV line's baseline.
    name_size, tv_size, leading = 30, 17, 26
    top = 90 - (0.67 * name_size + leading) / 2
    name, name_end = text_path("source_serif_4_regular.ttf", "Silicon Extend", name_size, text_x, top + 0.67 * name_size, -0.03)
    tv, _ = text_path("ibm_plex_mono_medium.ttf", "TV", tv_size, text_x + 1, top + 0.67 * name_size + leading, 0.12)
    assert name_end < 320 - 24, f"the name runs to {name_end:.1f} dp"
    s = mark_size / 44
    xml = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- 320x180 dp Android TV launcher banner: the cobalt Extend mark on Interface's paper and the app's
     TV name, "Silicon Extend TV" (Source Serif 4 and IBM Plex Mono outlines).
     Generated by tools/banner/make_tv_banner.py; edit that, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="320dp" android:height="180dp"
    android:viewportWidth="320" android:viewportHeight="180">
    <path android:fillColor="{PAPER}" android:pathData="M0 0h320v180h-320z" />
    <group android:translateX="{mark_x:g}" android:translateY="{mark_y:g}" android:scaleX="{s:.4f}" android:scaleY="{s:.4f}">
        <path android:fillColor="{COBALT}" android:pathData="{MARK}" />
    </group>
    <path android:fillColor="{INK}" android:pathData="{name}" />
    <path android:fillColor="{COBALT}" android:pathData="{tv}" />
</vector>
"""
    out = os.path.join(RES, "drawable", "tv_banner.xml")
    with open(out, "w") as f:
        f.write(xml)
    print(f"wrote {out}; the name ends at {name_end:.1f} dp")


if __name__ == "__main__":
    main()
