//! Installed apps on Windows, as the Start menu lists them (`Get-StartApps`).

use serde::Deserialize;

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct StartApp {
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "AppID")]
    pub app_id: String,
}

/// Parses `Get-StartApps | ConvertTo-Json` (a single app is an object, several an array).
pub fn parse_start_apps(json: &str) -> Result<Vec<StartApp>, String> {
    let trimmed = json.trim();
    if trimmed.is_empty() {
        return Ok(vec![]);
    }
    let value: serde_json::Value = serde_json::from_str(trimmed).map_err(|e| format!("couldn't read the Start menu app list: {e}"))?;
    let items = match value {
        serde_json::Value::Array(items) => items,
        obj @ serde_json::Value::Object(_) => vec![obj],
        _ => return Err("the Start menu app list wasn't a list".into()),
    };
    let mut apps: Vec<StartApp> = items
        .into_iter()
        .filter_map(|v| serde_json::from_value::<StartApp>(v).ok())
        .filter(|a| !a.name.trim().is_empty() && !a.app_id.trim().is_empty())
        .collect();
    apps.sort_by_key(|a| a.name.to_lowercase());
    apps.dedup();
    Ok(apps)
}

/// Windows' own tools and shell folders, hidden from `apps` unless `--all` is given (like
/// agent-device hides system apps).
pub fn is_system_app(app: &StartApp) -> bool {
    let id = app.app_id.to_ascii_lowercase();
    id.starts_with("microsoft.windows.")
        || id.starts_with("windows.")
        || id.starts_with('{')
        || id.starts_with("microsoft.autogenerated.")
        || id.contains("\\windowspowershell\\")
}

pub fn visible_apps(apps: &[StartApp], all: bool) -> Vec<&StartApp> {
    apps.iter().filter(|a| all || !is_system_app(a)).collect()
}

/// agent-device's `apps` text: one `Name (id)` line per app.
pub fn apps_text(apps: &[&StartApp], all: bool) -> String {
    let mut out = String::new();
    if !all {
        out.push_str("Showing user-installed apps. Use --all to include Windows' own apps.\n");
    }
    for a in apps {
        out.push_str(&format!("{} ({})\n", a.name, a.app_id));
    }
    out
}

/// Finds the app a Silicon named: exact name, exact id, then a name that starts with or contains
/// the query (case-insensitive). Ambiguous partial matches pick the shortest name.
pub fn resolve<'a>(apps: &'a [StartApp], query: &str) -> Option<&'a StartApp> {
    let q = query.trim().to_lowercase();
    if q.is_empty() {
        return None;
    }
    let exact = apps.iter().find(|a| a.name.to_lowercase() == q || a.app_id.to_lowercase() == q);
    if exact.is_some() {
        return exact;
    }
    let shortest = |it: Vec<&'a StartApp>| it.into_iter().min_by_key(|a| a.name.len());
    shortest(apps.iter().filter(|a| a.name.to_lowercase().starts_with(&q)).collect())
        .or_else(|| shortest(apps.iter().filter(|a| a.name.to_lowercase().contains(&q)).collect()))
}

/// Up to `n` app names close to `query`, for "not found" messages.
pub fn suggestions(apps: &[StartApp], query: &str, n: usize) -> Vec<String> {
    let q = query.trim().to_lowercase();
    let first = q.split_whitespace().next().unwrap_or("").to_owned();
    apps.iter()
        .filter(|a| !first.is_empty() && a.name.to_lowercase().contains(&first))
        .take(n)
        .map(|a| a.name.clone())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"[
      {"Name":"Notepad","AppID":"Microsoft.WindowsNotepad_8wekyb3d8bbwe!App"},
      {"Name":"Calculator","AppID":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"},
      {"Name":"Command Prompt","AppID":"{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\cmd.exe"},
      {"Name":"Visual Studio Code","AppID":"Microsoft.VisualStudioCode"},
      {"Name":"Settings","AppID":"windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel"},
      {"Name":"Notepad++","AppID":"C:\\Program Files\\Notepad++\\notepad++.exe"},
      {"Name":"","AppID":"x"}
    ]"#;

    #[test]
    fn parses_and_sorts() {
        let apps = parse_start_apps(SAMPLE).unwrap();
        assert_eq!(apps.len(), 6);
        assert_eq!(apps[0].name, "Calculator");
        let one = parse_start_apps(r#"{"Name":"Paint","AppID":"Microsoft.Paint_8wekyb3d8bbwe!App"}"#).unwrap();
        assert_eq!(one.len(), 1);
        assert!(parse_start_apps("").unwrap().is_empty());
        assert!(parse_start_apps("not json").is_err());
    }

    #[test]
    fn hides_system_apps_unless_all() {
        let apps = parse_start_apps(SAMPLE).unwrap();
        let user: Vec<_> = visible_apps(&apps, false).iter().map(|a| a.name.as_str()).collect();
        assert_eq!(user, vec!["Calculator", "Notepad", "Notepad++", "Visual Studio Code"]);
        assert_eq!(visible_apps(&apps, true).len(), 6);
        let text = apps_text(&visible_apps(&apps, false), false);
        assert!(text.starts_with("Showing user-installed apps"));
        assert!(text.contains("Notepad (Microsoft.WindowsNotepad_8wekyb3d8bbwe!App)\n"));
    }

    #[test]
    fn resolves_names() {
        let apps = parse_start_apps(SAMPLE).unwrap();
        assert_eq!(resolve(&apps, "notepad").unwrap().name, "Notepad");
        assert_eq!(resolve(&apps, "Microsoft.VisualStudioCode").unwrap().name, "Visual Studio Code");
        assert_eq!(resolve(&apps, "calc").unwrap().name, "Calculator");
        assert_eq!(resolve(&apps, "studio").unwrap().name, "Visual Studio Code");
        assert!(resolve(&apps, "photoshop").is_none());
        assert!(resolve(&apps, " ").is_none());
        assert_eq!(suggestions(&apps, "note pad", 5), vec!["Notepad".to_string(), "Notepad++".to_string()]);
    }
}
