[package]
name = "extend-driver"
description = "The interface every Silicon Extend device driver implements"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
extend-protocol.workspace = true
async-trait.workspace = true
serde_json.workspace = true
uuid.workspace = true
tokio = { workspace = true }
